import numpy as np
arr = np.arange(0,10)
print("Array original")
print(arr)
print("array somado a ele mesmo")
print(arr+arr)
print("Array subtraido por ele mesmo")
print(arr-arr)
print("Array multiplicado por ele mesmo")
print(arr*arr)
print("array dividido por ele mesmo\nem divisao por zero recebemos um warning mas nao um erro")
print(arr/arr)
print("em 1/0 tambem recebemos um warning mas o item do array recebe valor diferente")
print(1/arr)
print("array ao cubo")
print(arr**3)

print("Universal Array Functions")
print("Referencia: "+str("http://docs.scipy.org/doc/numpy/reference/ufuncs.html"))
print("Raiz quadrada aplicada ao array")
print(np.sqrt(arr))
print("exponencial e^")
print(np.exp(arr))
print("Numero mais alto")
print(np.max(arr))
print("seno")
print(np.sin(arr))
print("logaritmo")
print(np.log(arr))